/**
 * Canonical route inventory for the 360 Flatmates web app.
 *
 * Each entry is a concrete URL sample (not a parameterised pattern).
 * Used by the route-contracts integration test to verify that every
 * documented route has a corresponding React Router route and vice-versa.
 */
export const routeInventory = [
  "/",
  "/discover",
  "/discover/koramangala-studio",
  "/search",
  "/search/semantic",
  "/stats",
  "/login",
  "/signup",
  "/forgot-password",
  "/auth/callback",
  "/onboarding",
  "/onboarding/mode",
  "/home",
  "/swipe",
  "/likes",
  "/matches",
  "/chats",
  "/chats/c-priya",
  "/compatibility/1",
  "/explore",
  "/post",
  "/post/review",
  "/manage",
  "/dashboard",
  "/dashboard/analytics",
  "/visits",
  "/visits/v-1",
  "/profile",
  "/profile/priya",
  "/profile/edit",
  "/settings",
  "/settings/appearance",
  "/settings/blocked-users",
  "/settings/notifications",
  "/settings/report-problem",
  "/notifications",
  "/saved-searches",
  "/alerts",
  "/my-listings/koramangala-studio/edit",
  "/my-listings/koramangala-studio",
  "/choose-role",
  "/location",
  "/help",
  "/verify",
  "/terms",
  "/privacy",
  "/about",
  "/maintenance",
  "/not-found",
  "/error",
  "/admin/stats",
  "/admin/moderation/listings",
  "/admin/moderation/reports",
  "/admin/moderation/prescreen/koramangala-studio",
] as const;
